	String aPPraiseeId ;
	String aPPraiseeName; 
	String grouPProject ;
	String assessmentFrom; 
	String assessmentTo ;
	String aPPraiserId ;
	String aPPraiserName; 
	String reviewerId ;
	String reviewerName; 
	String P1 ;
	String P2 ;
	String P3 ;
	String P4 ;
	String P5 ;
	String P6 ;
	String P7 ;
	String P8 ;
	String P9 ;
	String P10 ;
	String P11 ;
	String P12 ;
	int PD1; 
	String Q1 ;
	String Q2 ;
	String Q3 ;
	String Q4 ;
	String Q5 ;
	String Q6 ;
	String Q7 ;
	String Q8 ;
	String Q9 ;
	int QD1 ;
	String JK1 ;
	String JK2 ;
	String JK3 ;
	String JK4 ;
	String JK5 ;
	String JK6 ;
	String JK7 ;
	int JKD1 ;
	String JResp1; 
	String JResp2 ;
	String JResp3 ;
	String JResp4 ;
	String JResp5 ;
	String JResp6 ;
	String JResp7 ;
	String JResp8 ;
	String JResp9 ;
	String JResp10 ;
	int JRespD1; 
	String PM1 ;
	String PM2 ;
	String PM3 ;
	String PM4 ;
	String PM5 ;
	String PM6 ;
	String PM7 ;
	int PMD1 ;
	String CA1 ;
	String CA2 ;
	String CA3 ;
	String CA4 ;
	String CA5 ;
	String CA6 ;
	String CA7 ;
	String CA8 ;
	String CA9 ;
	int CAD1 ;
	String PII1 ;
	String PII2 ;
	String PII3 ;
	String PII4 ;
	String PII5 ;
	String PII6 ;
	String PII7 ;
	String PII8 ;
	String PII9 ;
	int PIID1 ;
	String Docu1 ;
	String Docu2 ;
	int DocuD1 ;
	String CI1 ;
	String CI2 ;
	String CI3 ;
	String CI4 ;
	int CID1 ;
	String HR1 ;
	String HR2 ;
	String HR3 ;
	String HR4 ;
	String HR5 ;
	String HR6 ;
	String HR7 ;
	String HR8 ;
	String HR9 ;
	int HRD1 ;
	String OR1 ;
	String OR2 ;
	String OR3 ;
	String OR4 ;
	String OR5 ;
	String OR6 ;
	String OR7 ;
	String OR8 ;
	String OR9 ;
	String OR10 ;
	String OR11 ;
	String OR12 ;
	int ORD1 ;
	int Average; 
	int TotalScore; 
	int OverallRating; 
	int OverallGrade ;
************************************************************************************************







}
