create table reviewer(aPPraiseeId varchar(15),
 				aPPraiseeName varchar(30),
			 	grouPProject varchar(60),
 				assessmentFrom varchar(30),
 				assessmentTo varchar(30),
				aPPraiserId varchar(15),
				aPPraiserName varchar(30),
				reviewerId varchar(15),
				reviewerName varchar(30),
				discussions_apse text,
				apse_attitude text,
				apse_presentresp text,
				apse_highresp text,
				comments_remarks text);
