/*
 * JSP generated by Resin-3.1.6 (built Sun, 04 May 2008 03:25:50 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;

public class _account_0admin__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, "/", session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=iso-8859-1");
    request.setCharacterEncoding("ISO-8859-1");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
       
if(session.getAttribute("user_name").toString().equals("admin") & "admin".equals(session.getAttribute("pwd").toString()) )
{

 
      out.write(_jsp_string1, 0, _jsp_string1.length);
       } 
      out.write(_jsp_string2, 0, _jsp_string2.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7072480922035483583L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("account_admin.jsp"), -1075437689854083082L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  static {
    _jsp_string0 = "\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n<title>SVS</title>\r\n</head>\r\n\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n<body background=\"images/bg.jpg\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\r\n\r\n<table align=\"center\" width=\"800\"bgcolor=\"#FFD3A2\" background=\"images/bg.jpg\">\r\n<tr>\r\n<td>\r\n\r\n\r\n\r\n<table width=\"804\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n  <tr>\r\n    <td><img src=\"images/banner.jpg\" width=\"800\"></td>\r\n  </tr>\r\n  \r\n</table>\r\n  <table width=\"800\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n  <tr>\r\n    <td background=\"images/after_main.jpg\" height=\"45\" align=\"center\"><strong><font color=\"#573801\" size=\"3\" face=\"verdana\">Welcome To Inventery Department</font></strong>      <!--<img src=\"images/after_main.jpg\">-->\r\n	\r\n	 \r\n	</td>\r\n  </tr>\r\n</table>\r\n\r\n  <p>&nbsp;</p>\r\n  <table align=\"center\"    >\r\n<tr>\r\n <td ><p><strong> <font  size = \"3\" face = \"verdana\" color=\"#573801\">Main Admin Details</font></strong></p>\r\n   \r\n    </td>\r\n</tr>\r\n\r\n</table>\r\n\r\n&nbsp;\r\n\r\n<table>\r\n\r\n<tr>\r\n\r\n<td>\r\n<form action=\"specific.jsp\">\r\n <input type=\"hidden\" name=\"username\" value=\"admin\"/>\r\n<input type=\"hidden\" name=\"password\" value=\"admin\"/>\r\n<input align =\"left\" type=\"image\" src=\"images/home.jpg\"/>\r\n\r\n</form>\r\n\r\n</td></tr></table>\r\n\r\n <table width=\"199\" align=\"center\">\r\n <tr>\r\n  <td align=\"center\">\r\n   <form action=\"account1_admin.jsp\">\r\n    <input type=\"submit\" value=\"        Accounting Package       \">\r\n   </form>\r\n   \r\n   </td>\r\n   </tr>\r\n   <tr>\r\n  <td align=\"center\">\r\n   <form action=\"department_details.jsp\">\r\n    <input type=\"submit\" value=\"         Department Details         \">\r\n   </form>\r\n   \r\n   </td>\r\n   </tr>\r\n \r\n   \r\n</table>\r\n   \r\n\r\n</td>\r\n</tr>\r\n</table>\r\n\r\n\r\n".toCharArray();
  }
}
