/*
 * JSP generated by Resin-3.1.6 (built Sun, 04 May 2008 03:25:50 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.util.Vector.*;
import java.sql.*;
import java.text.*;

public class _balancesheet_0main__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
       
boolean admin_check = false;
boolean admin = false;
if(session.getAttribute("user_name").toString().equals("admin_account") & "admin_account".equals(session.getAttribute("pwd").toString()) )
{
	admin_check = true;
}
else if(session.getAttribute("user_name").toString().equals("admin") & "admin".equals(session.getAttribute("pwd").toString()) )
{
	admin = true;
}

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
if(admin_check || admin)
{

 
      out.write(_jsp_string2, 0, _jsp_string2.length);
       if(admin_check){ 
      out.write(_jsp_string3, 0, _jsp_string3.length);
       } 
      out.write(_jsp_string1, 0, _jsp_string1.length);
       if(admin){ 
      out.write(_jsp_string4, 0, _jsp_string4.length);
       } 
      out.write(_jsp_string5, 0, _jsp_string5.length);
       if(admin_check){ 
      out.write(_jsp_string3, 0, _jsp_string3.length);
       } 
      out.write(_jsp_string1, 0, _jsp_string1.length);
       if(admin){ 
      out.write(_jsp_string4, 0, _jsp_string4.length);
       } 
      out.write(_jsp_string6, 0, _jsp_string6.length);
       Class.forName("com.mysql.jdbc.Driver");
   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/kvk","root","root");
   Statement st=con.createStatement();
   
      out.write(_jsp_string7, 0, _jsp_string7.length);
      
					String t = "gfsd";
					double dr_gr_tot=0.0;
					double open_stk_b=0.0;
					
					DecimalFormat df = new DecimalFormat("#.##");
					
					////
					
					
					String ps=" select sum(balance) from current_assets where  under='PurchaseAccounts'  ";
				ResultSet prs=st.executeQuery(ps);
				prs.next();
				
				double purchase_b=prs.getDouble(1);
				
				
				
				/////
				
				String dpys=" select sum(balance) from current_assets where  under='DirectExpenses' ";
				ResultSet dpyrs=st.executeQuery(dpys);
				dpyrs.next();
				
				double dir_exp_b=0.0;
				
				dir_exp_b = dpyrs.getDouble(1);
				////
				
				String pys=" select sum(balance) from current_assets where under='IndirectExpenses' ";
				ResultSet pyrs=st.executeQuery(pys);
				pyrs.next();
				
				double indir_exp_b=0;
				indir_exp_b = pyrs.getDouble(1);
				
				//String pys1=" select particulars from voucher_payment ,ledgersdata where ledgername=particulars and under='IndirectExpenses' ";
				//ResultSet pyrs1=st.executeQuery(pys1);
				//while(pyrs1.next())
				//{
					//out.println(pyrs1.getString(1));
				//session.setAttribute("parti",pyrs1.getString(1));
				//}
				
				
				/////
				
				
				String ss=" select sum(balance) from current_assets where  under='SalesAccounts'  ";
				ResultSet srs=st.executeQuery(ss);
				srs.next();
				
				double sales_b = 0;
				sales_b = srs.getDouble(1);
				
				
				/////
				
				
				String sdin=" select sum(balance) from current_assets where  under='DirectIncomes'  ";
				ResultSet sdinrs=st.executeQuery(sdin);
				sdinrs.next();
				
				double dir_income_b=0.0;
				dir_income_b = sdinrs.getDouble(1);
				
				////
				
				
				
				
				
				String sindin=" select sum(balance) from current_assets where  under='IndirectIncomes'  ";
				ResultSet sindinrs=st.executeQuery(sindin);
				sindinrs.next();
				
				double indir_income_b=0.0;
				indir_income_b = sindinrs.getDouble(1);
				
				
				/////
				
				String cs=" select sum(balance) from closing_stock";
				ResultSet crs=st.executeQuery(cs);
				crs.next();
				
				double cl_stk_b=0;
				cl_stk_b = crs.getDouble(1);
				
				////
				
				
					dr_gr_tot = purchase_b + dir_exp_b + open_stk_b;
					
					double cr_grs_tot = 0.0;
					
					cr_grs_tot = sales_b + dir_income_b + cl_stk_b  ;
					
					double tot = 0.0;
					
					double gross_prf_b = 0.00;
					double gross_prf_c = 0.00;
				
				if( dr_gr_tot < cr_grs_tot)
				{
					gross_prf_c = cr_grs_tot - dr_gr_tot ;
					t = "dr";
					tot = cr_grs_tot;
				}
				else
				{
					gross_prf_b = dr_gr_tot - cr_grs_tot ;
					t = "cr"; 
					tot = dr_gr_tot;
				}
				//out.println("greater :" + t);
				
				///////
				
				double net_loss = 0.0;
				double net_profit = 0.0;
				double net_tot = 0.0;
				double dr_net = 0.0;
				double cr_net = 0.0;
				
				dr_net =  indir_exp_b + gross_prf_b;
				cr_net = gross_prf_c + indir_income_b;
				
				session.setAttribute("netpr" , net_profit);
				session.setAttribute("netls" , net_loss);
				String net = null;
				if(dr_net < cr_net)
				{
					net_profit = cr_net - dr_net;
					net_tot = cr_net;
					net="pr";
					session.setAttribute("netpr" , net_profit);
					//out.println(net_profit);
				}
				else
				{
					net_loss = dr_net - cr_net;
					net_tot = dr_net;
					net="ls";
					session.setAttribute("netls" , net_loss);
					//out.println(net_loss);
					
				}
				
				 
				
				
				
				
				
				
				
				
				
				

      out.write(_jsp_string8, 0, _jsp_string8.length);
       
 	
 	
	String netpr = session.getAttribute("netpr").toString();
	double net_pr = Double.parseDouble(netpr);
	//out.println("pr: " +net_pr);
	
	String netls = session.getAttribute("netls").toString();
	double net_ls = Double.parseDouble(netls);
	//out.println("ls: " +net_ls);
	
	//String ss = session.getAttribute("ss").toString();
	//out.println("ls: " +ss);
	
 
  
      out.write(_jsp_string9, 0, _jsp_string9.length);
       
 		String sca = "select sum(balance) from current_assets where  under='CapitalAccount' "; //,ledgersdata where particulars=ledgername and under='CapitalAccount' ";
		ResultSet rca = st.executeQuery(sca);
		double ca = 0.0;
		while(rca.next())
		{
		
		ca = rca.getDouble(1);
		}
		//////////
		
		double crn_lia = 0.0;
		
		String scrnl = "select sum(balance) from current_assets where  under='SundryCreditors' "; //,ledgersdata where particulars=ledgername and under='CapitalAccount' ";
		ResultSet rcrnl = st.executeQuery(scrnl);
		
		while(rcrnl.next())
		{
		
		crn_lia = rcrnl.getDouble(1);
		
		}
		crn_lia = -crn_lia;
		
		////////////////
				
		double cra1 = 0.0;
		String scra="select sum(balance) from current_assets where ( under='BankAccounts') | (  under='Cash-in-hand' ) | (  under='SundryDebtors' ) | (  under='CurrentAssets' )";

		ResultSet rcra=st.executeQuery(scra);
	   
		while(rcra.next())
		{
			cra1 = rcra.getDouble(1);
		}
		
		////////////
		//String scra = "select sum(amount) from voucher_receipt,ledgersdata where particulars=ledgername and (under='CurrentAssets' | under='BankAccounts' | under='Cash-in-Hand' ) ";
		//ResultSet rcra = st.executeQuery(scra);
		
		//double cra1 = 0.0;
		
		//while(rcra.next())
		//{
		//cra1 = rcra.getDouble(1);
 		//}
		
		//////////////
		String scs = "select sum(balance) from closing_stock ";
		ResultSet rcs = st.executeQuery(scs);
		
		double cs1 = 0.0;
		
		while(rcs.next())
		{
		cs1 = rcs.getDouble(1);
 		}
		
		
		
		double cra = cra1 + cs1;
		
		//////////
		
		String sl = "select sum(balance) from current_assets where under='Loans(Liability)' "; //"select sum(amount) from voucher_receipt,ledgersdata where particulars=ledgername and under='Loans(Liability)' ";
		ResultSet rl = st.executeQuery(sl);
		
		double loans = 0.0;
		
		while(rl.next())
		{
		loans = rl.getDouble(1);
 		}
		
		
		
		
		
 
  
      out.write(_jsp_string10, 0, _jsp_string10.length);
       

	double tot_lia = 0.0;
	double tot_ass = 0.0;
	
	tot_lia = ca + loans + net_pr + crn_lia;
	tot_ass = cra +net_ls ;
	
	
	
 
      out.write(_jsp_string11, 0, _jsp_string11.length);
       out.print(ca); 
      out.write(_jsp_string12, 0, _jsp_string12.length);
      
				
				out.print(loans);
			
      out.write(_jsp_string13, 0, _jsp_string13.length);
      	
					
					out.print(crn_lia);
				
      out.write(_jsp_string14, 0, _jsp_string14.length);
       
			if(net_pr!=0)
			{ 
			
      out.write(_jsp_string15, 0, _jsp_string15.length);
      	
					
					out.print(df.format(net_pr));
				
      out.write(_jsp_string16, 0, _jsp_string16.length);
       
			}
			 
      out.write(_jsp_string17, 0, _jsp_string17.length);
      
				
				out.print(cra);
			
      out.write(_jsp_string18, 0, _jsp_string18.length);
       
			if(net_ls!=0)
			{ 
			
      out.write(_jsp_string15, 0, _jsp_string15.length);
      	
					
					out.print(df.format(net_ls));
				
      out.write(_jsp_string16, 0, _jsp_string16.length);
       
			}
			 
      out.write(_jsp_string19, 0, _jsp_string19.length);
       out.println(tot_lia); 
      out.write(_jsp_string20, 0, _jsp_string20.length);
       out.println(tot_ass); 
      out.write(_jsp_string21, 0, _jsp_string21.length);
       } 
      out.write(_jsp_string22, 0, _jsp_string22.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7072480922035483583L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("balancesheet_main.jsp"), -759629031761188406L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("dummy.jsp"), -5574626835266838244L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string6;
  private final static char []_jsp_string13;
  private final static char []_jsp_string7;
  private final static char []_jsp_string8;
  private final static char []_jsp_string0;
  private final static char []_jsp_string20;
  private final static char []_jsp_string22;
  private final static char []_jsp_string18;
  private final static char []_jsp_string10;
  private final static char []_jsp_string21;
  private final static char []_jsp_string19;
  private final static char []_jsp_string16;
  private final static char []_jsp_string15;
  private final static char []_jsp_string12;
  private final static char []_jsp_string4;
  private final static char []_jsp_string17;
  private final static char []_jsp_string9;
  private final static char []_jsp_string11;
  private final static char []_jsp_string14;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  static {
    _jsp_string3 = "\r\n<form action=\"kvk_finance_main.jsp\" method=\"post\">\r\n".toCharArray();
    _jsp_string2 = "\r\n\r\n <BODY background=\"images/bg.jpg\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\r\n  <table width=\"800\"  border = \"0\" cellspacing = \"0\" cellpadding = \"0\" align =\"center\">\r\n <tr>\r\n 	<td><img src = \"images/banner.jpg\" width = \"800\"></td>\r\n </tr>\r\n </table>\r\n\r\n <table width = \"800\" border = \"0\" cellspacing = \"0\" cellpadding = \"0\" align = \"center\">\r\n <tr>\r\n <td background = \"images/after_main.jpg\" height = \"41\" align = \"center\" ><strong> <font color = \"#573801\" size = \"3\" \r\n face = \"verdana\"> Welcome To Finance Department</font></strong> </td>\r\n </tr>\r\n </table>\r\n<p>&nbsp;</p>\r\n\r\n<table align=\"center\"    >\r\n<tr>\r\n <td ><strong> <font  face = \"verdana\" size = \"3\" color=\"#573801\" >Balance Sheet </font></strong>\r\n</td>\r\n</tr>\r\n\r\n</table>\r\n\r\n<table>\r\n\r\n".toCharArray();
    _jsp_string6 = "\r\n\r\n<input align =\"right\" type=\"image\" src=\"images/back.jpg\"/>\r\n</form>\r\n</td>\r\n\r\n</tr>\r\n</table>\r\n<!-- Strip whitespace -->\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string13 = "\r\n			</td></tr>\r\n			\r\n			\r\n			<tr ><td witdh=\"250\"><a href=\"current_liabilities.jsp\"><strong> <font   face=\"Times New Roman, Times, serif\">Current&nbsp;Liabilities</font></strong></a></td> <td align=\"right\" width=\"300\">\r\n				".toCharArray();
    _jsp_string7 = "\r\n   \r\n<HTML>\r\n <HEAD>\r\n \r\n<title>SVS</title>\r\n   </HEAD>\r\n\r\n\r\n\r\n <BODY>\r\n ".toCharArray();
    _jsp_string8 = "\r\n \r\n\r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n </BODY>\r\n</HTML>\r\n\r\n\r\n ".toCharArray();
    _jsp_string0 = "<!-- Strip whitespace -->\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n<HTML>\r\n <HEAD>\r\n  <title>SVS</title>\r\n   </HEAD>\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string20 = "</font></strong></td></tr></table></td>\r\n		<td><table height=\"50\"><tr><td width=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\">Total</font></strong></td>  <td width=\"350\" align=\"right\"><strong> <font   face=\"Times New Roman, Times, serif\"> ".toCharArray();
    _jsp_string22 = "\r\n\r\n\r\n\r\n </BODY>\r\n</HTML>\r\n".toCharArray();
    _jsp_string18 = "</td>\r\n			</tr>\r\n			\r\n			\r\n			".toCharArray();
    _jsp_string10 = "\r\n \r\n".toCharArray();
    _jsp_string21 = "</font></strong></td></tr></table></td>\r\n	</tr>\r\n	\r\n	\r\n	</table>\r\n	\r\n	\r\n			\r\n\r\n</td>\r\n</tr>\r\n</table>\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string19 = "\r\n			\r\n			<tr ><td  height=\"100\"></td> </tr> \r\n			<tr ><td  height=\"100\"></td> </tr> \r\n			\r\n			\r\n			 \r\n		</table>\r\n	</td>\r\n	</tr>\r\n	\r\n	\r\n	\r\n	<tr>\r\n		<td><table height=\"50\"><tr><td width=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\">Total</font></strong></td> <td width=\"350\" align=\"right\"><strong> <font   face=\"Times New Roman, Times, serif\"> ".toCharArray();
    _jsp_string16 = "\r\n			</td></tr>\r\n			".toCharArray();
    _jsp_string15 = "\r\n			\r\n			<tr ><td witdh=\"250\"><a href=\"Profit&Loss_main.jsp\"><strong> <font   face=\"Times New Roman, Times, serif\">Profit&nbsp;&&nbsp;Loss&nbsp;A/c</font></strong></a></td> <td align=\"right\" width=\"300\">\r\n				".toCharArray();
    _jsp_string12 = "\r\n				\r\n			</td></tr> \r\n			<tr ><td witdh=\"250\"><a href=\"loans_liability.jsp\"><strong> <font   face=\"Times New Roman, Times, serif\">Loans&nbsp;(Liability)</font></strong></a></td> <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string4 = "\r\n<form action=\"account1_admin.jsp\" method=\"post\">\r\n".toCharArray();
    _jsp_string17 = "\r\n			\r\n			\r\n			\r\n			\r\n			<tr ><td  height=\"100\"></td> </tr> \r\n			\r\n			\r\n			\r\n			\r\n			\r\n			\r\n			\r\n			\r\n		</table>\r\n	</td>\r\n	<td>\r\n		<table width=\"400\" border=\"0\" height=\"300\" bgcolor=\"#FADFC3\" bordercolor=\"#F0B269\" cellpadding=\"0\" cellspacing=\"0\" >\r\n			<tr ><td witdh=\"250\"><a href=\"current_assets.jsp\"><strong> <font   face=\"Times New Roman, Times, serif\">Current&nbsp;Assets</font></strong></a></td> <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string9 = "\r\n\r\n ".toCharArray();
    _jsp_string11 = "\r\n\r\n\r\n<table width=\"800\" align=\"center\" height=\"300\"  >\r\n\r\n<tr>\r\n\r\n<td>\r\n	<table width=\"800\" height=\"300\"  border=\"1\"  bgcolor=\"#FADFC3\" bordercolor=\"#F0B269\" >\r\n	<tr>\r\n		<td><table height=\"50\"><tr><td width=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\"> </font></strong></td> <td width=\"350\"><strong> <font   face=\"Times New Roman, Times, serif\"> Liabilities</font></strong></td></tr></table></td>\r\n		<td><table height=\"50\"><tr><td width=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\"></font></strong></td> <td width=\"350\"><strong> <font   face=\"Times New Roman, Times, serif\"> Assets</font></strong></td></tr></table></td>\r\n	</tr>\r\n	<tr>\r\n	<td>\r\n		<table width=\"400\"  border=\"0\" height=\"300\" bgcolor=\"#FADFC3\" bordercolor=\"#F0B269\" cellpadding=\"0\"  cellspacing=\"0\">	\r\n			<tr ><td witdh=\"250\"><a href=\"capital_account.jsp\"><strong> <font   face=\"Times New Roman, Times, serif\">Capital&nbsp;Account</font></strong></a></td> <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string14 = "\r\n			</td></tr>\r\n			\r\n			".toCharArray();
    _jsp_string5 = "\r\n\r\n\r\n<tr>\r\n<td width=\"300\"/>\r\n\r\n<td>\r\n<input align =\"left\" type=\"image\" src=\"images/home.jpg\"/>\r\n</form>\r\n</td>\r\n\r\n<td width=\"600\"></td>\r\n<td>\r\n".toCharArray();
    _jsp_string1 = "\r\n\r\n".toCharArray();
  }
}
