/*
 * JSP generated by Resin-3.1.6 (built Sun, 04 May 2008 03:25:50 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.util.Vector.*;
import java.sql.*;

public class _fn_0acc_0sl_0sales__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
       Class.forName("com.mysql.jdbc.Driver");
   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/kvk","root","root");
   Statement st=con.createStatement();
   
      out.write(_jsp_string1, 0, _jsp_string1.length);
       
boolean admin_check = false;
boolean admin = false;
boolean fn_check = false;
boolean sl_ad= false;
if(session.getAttribute("user_name").toString().equals("fn_account") & "fn_account".equals(session.getAttribute("pwd").toString()) )
{
	fn_check = true;
}
if(session.getAttribute("user_name").toString().equals("admin_account") & "admin_account".equals(session.getAttribute("pwd").toString()) )
{
	admin_check = true;
}
 if(session.getAttribute("user_name").toString().equals("admin") & "admin".equals(session.getAttribute("pwd").toString()) )
{
	admin = true;
}

if(session.getAttribute("user_name").toString().equals("sales_admin") & "sales_admin".equals(session.getAttribute("pwd").toString()) )
sl_ad=true;



      out.write(_jsp_string2, 0, _jsp_string2.length);
      
if(admin_check || admin || fn_check || sl_ad)
{

 
      out.write(_jsp_string3, 0, _jsp_string3.length);
       if(fn_check){ 
      out.write(_jsp_string4, 0, _jsp_string4.length);
       } 
      out.write(_jsp_string2, 0, _jsp_string2.length);
       if(admin_check){ 
      out.write(_jsp_string5, 0, _jsp_string5.length);
       } 
      out.write(_jsp_string2, 0, _jsp_string2.length);
       if(admin){ 
      out.write(_jsp_string6, 0, _jsp_string6.length);
       } 
      out.write(_jsp_string2, 0, _jsp_string2.length);
       if(sl_ad){ 
      out.write(_jsp_string7, 0, _jsp_string7.length);
       } 
      out.write(_jsp_string8, 0, _jsp_string8.length);
       
if(sl_ad)
	{ }
else
if(admin){ 
      out.write(_jsp_string9, 0, _jsp_string9.length);
       }

else
{

      out.write(_jsp_string10, 0, _jsp_string10.length);
       } 
      out.write(_jsp_string11, 0, _jsp_string11.length);
       
		double tot = 0.0;
		String ps="select * from sl_sales";
		ResultSet prs=st.executeQuery(ps);
	    int i=0;
		while(prs.next())
		{
		i++;
	
      out.write(_jsp_string12, 0, _jsp_string12.length);
       out.println(prs.getString(1));
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(prs.getString(2));
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(prs.getString(3));
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(prs.getString(4));
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(prs.getString(5));
      out.write(_jsp_string14, 0, _jsp_string14.length);
       out.println(prs.getInt(6));
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(prs.getString(7));
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(prs.getDouble(8));
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(prs.getDouble(9));
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(prs.getString(10));
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(prs.getString(11));
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(prs.getString(12));
      out.write(_jsp_string15, 0, _jsp_string15.length);
       
		tot = tot + prs.getDouble(9);
		
		
		}
		
	
      out.write(_jsp_string16, 0, _jsp_string16.length);
       out.println(tot); 
      out.write(_jsp_string17, 0, _jsp_string17.length);
      
 	if(admin_check || fn_check ) 
	{
 
  
      out.write(_jsp_string18, 0, _jsp_string18.length);
       if(fn_check) { 
      out.write(_jsp_string19, 0, _jsp_string19.length);
       } 
      out.write(_jsp_string20, 0, _jsp_string20.length);
       if(admin_check) { 
      out.write(_jsp_string21, 0, _jsp_string21.length);
       } 
      out.write(_jsp_string22, 0, _jsp_string22.length);
       } 
      out.write(_jsp_string23, 0, _jsp_string23.length);
       } 
      out.write(_jsp_string24, 0, _jsp_string24.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7072480922035483583L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("fn_acc_sl_sales.jsp"), -6659714641414062353L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string10;
  private final static char []_jsp_string6;
  private final static char []_jsp_string0;
  private final static char []_jsp_string13;
  private final static char []_jsp_string22;
  private final static char []_jsp_string20;
  private final static char []_jsp_string7;
  private final static char []_jsp_string15;
  private final static char []_jsp_string8;
  private final static char []_jsp_string9;
  private final static char []_jsp_string23;
  private final static char []_jsp_string11;
  private final static char []_jsp_string16;
  private final static char []_jsp_string14;
  private final static char []_jsp_string17;
  private final static char []_jsp_string1;
  private final static char []_jsp_string19;
  private final static char []_jsp_string4;
  private final static char []_jsp_string5;
  private final static char []_jsp_string21;
  private final static char []_jsp_string18;
  private final static char []_jsp_string3;
  private final static char []_jsp_string24;
  private final static char []_jsp_string12;
  private final static char []_jsp_string2;
  static {
    _jsp_string10 = "\r\n\r\n<form action=\"fn_acc_sales.jsp\" method=\"post\">\r\n<input align =\"left\" type=\"image\" src=\"images/back.jpg\"/>\r\n</form>\r\n".toCharArray();
    _jsp_string6 = "\r\n<input type=\"hidden\" name=\"username\" value=\"admin\"/>\r\n<input type=\"hidden\" name=\"password\" value=\"admin\"/>\r\n".toCharArray();
    _jsp_string0 = "<!-- Strip whitespace -->\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string13 = "</td>\r\n		<td align=\"center\"> ".toCharArray();
    _jsp_string22 = "\r\n  \r\n    <input type=\"submit\" value=\"        Accounting Package       \">\r\n   </form>\r\n   \r\n   </td>\r\n   </tr>\r\n   \r\n  </table>\r\n\r\n".toCharArray();
    _jsp_string20 = "\r\n  \r\n  ".toCharArray();
    _jsp_string7 = "\r\n<input type=\"hidden\" name=\"username\" value=\"sales_admin\"/>\r\n<input type=\"hidden\" name=\"password\" value=\"sales_admin\"/>\r\n".toCharArray();
    _jsp_string15 = "</td>\r\n		\r\n		\r\n		\r\n	</tr>\r\n	\r\n	".toCharArray();
    _jsp_string8 = "\r\n<input align =\"left\" type=\"image\" src=\"images/home.jpg\"/>\r\n</form>\r\n</td>\r\n\r\n<td width=\"600\"/>\r\n\r\n<td>\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string9 = "\r\n<form action=\"sales2.jsp\" method=\"post\">\r\n<input align =\"left\" type=\"image\" src=\"images/back.jpg\"/>\r\n</form>\r\n".toCharArray();
    _jsp_string23 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string11 = "\r\n\r\n</td>\r\n\r\n\r\n</tr>\r\n\r\n</table>\r\n \r\n\r\n \r\n <table align=\"center\"    >\r\n   <tr>\r\n     <td ><strong> <font  face = \"verdana\"  size = \"3\"  color=\"#573801\" >Sales Details</font></strong> </td>\r\n   </tr>\r\n </table>\r\n <p>&nbsp;</p>\r\n \r\n <table align=\"center\" width=\"1000\" border=\"1\"  bgcolor=\"#FADFC3\" bordercolor=\"#F0B269\">\r\n 	<tr>\r\n		<td align=\"center\"> <strong><font   face=\"Times New Roman, Times, serif\">Date</font></strong></td>\r\n		<td align=\"center\"> <strong><font   face=\"Times New Roman, Times, serif\">Party Name</font></strong></td>\r\n		<td align=\"center\"> <strong><font   face=\"Times New Roman, Times, serif\">Quatation No.</font></strong></td>\r\n		<td align=\"center\"> <strong><font   face=\"Times New Roman, Times, serif\">Item Code</font></strong></td>\r\n		\r\n		<td align=\"center\"> <strong><font   face=\"Times New Roman, Times, serif\">Item Name</font></strong></td>\r\n		<td align=\"center\"> <strong><font   face=\"Times New Roman, Times, serif\">Quantity</font></strong></td>\r\n		<td align=\"center\"> <strong><font   face=\"Times New Roman, Times, serif\">Measurment</font></strong></td>\r\n		<td align=\"center\"> <strong><font   face=\"Times New Roman, Times, serif\">Rate</font></strong></td>\r\n		<td align=\"center\"> <strong><font   face=\"Times New Roman, Times, serif\">Amount</font></strong></td>\r\n		<td align=\"center\"> <strong><font   face=\"Times New Roman, Times, serif\">Cheque No.</font></strong></td>\r\n		<td align=\"center\"> <strong><font   face=\"Times New Roman, Times, serif\">Bank Name</font></strong></td>\r\n		<td align=\"center\"> <strong><font   face=\"Times New Roman, Times, serif\">Narration</font></strong></td>\r\n	</tr>\r\n	".toCharArray();
    _jsp_string16 = "\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n	\r\n </table>\r\n \r\n \r\n <table align=\"center\" width=\"1000\" border=\"1\"  bgcolor=\"#FADFC3\" bordercolor=\"#F0B269\">\r\n <tr>\r\n <td align=\"right\" width=\"1100\">\r\n  <strong><font   face=\"Times New Roman, Times, serif\">Total</font></strong>\r\n </td>\r\n <td width=\"500\">\r\n ".toCharArray();
    _jsp_string14 = "</td>\r\n		\r\n		<td align=\"center\"> ".toCharArray();
    _jsp_string17 = "\r\n </td>\r\n </tr>\r\n </table>\r\n \r\n \r\n \r\n <p>&nbsp;</p>\r\n ".toCharArray();
    _jsp_string1 = "\r\n<HTML>\r\n <HEAD>\r\n  <title>SVS</title>\r\n  <script type=\"text/javascript\">\r\n  	function f1()\r\n	{\r\n		var s=document.getElementById(\"id1\").value;\r\n		var v=2;\r\n		\r\n	}\r\n		\r\n		\r\n  \r\n  </script>\r\n   </HEAD>\r\n   \r\n   ".toCharArray();
    _jsp_string19 = "\r\n  <form action=\"account_operator.jsp\">\r\n  ".toCharArray();
    _jsp_string4 = "\r\n<input type=\"hidden\" name=\"username\" value=\"fn_account\"/>\r\n<input type=\"hidden\" name=\"password\" value=\"fn_account\"/>\r\n".toCharArray();
    _jsp_string5 = "\r\n<input type=\"hidden\" name=\"username\" value=\"admin_account\"/>\r\n<input type=\"hidden\" name=\"password\" value=\"admin_account\"/>\r\n".toCharArray();
    _jsp_string21 = "\r\n   <form action=\"kvk_finance_main.jsp\">\r\n  ".toCharArray();
    _jsp_string18 = "\r\n  \r\n  <table width = \"199\" align = \"center\">\r\n <tr>\r\n  <td align=\"center\">\r\n  \r\n  ".toCharArray();
    _jsp_string3 = "\r\n\r\n\r\n <BODY background=\"images/bg.jpg\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\r\n  <table width=\"800\"  border = \"0\" cellspacing = \"0\" cellpadding = \"0\" align =\"center\">\r\n <tr>\r\n 	<td><img src = \"images/banner.jpg\" width = \"800\"></td>\r\n </tr>\r\n </table>\r\n\r\n <table width = \"800\" border = \"0\" cellspacing = \"0\" cellpadding = \"0\" align = \"center\">\r\n <tr>\r\n <td background = \"images/after_main.jpg\" height = \"41\" align = \"center\" ><strong> <font color = \"#573801\" size = \"3\" \r\n face = \"verdana\"> Welcome To Finance Department</font></strong> </td>\r\n </tr>\r\n </table>\r\n<p>&nbsp;</p>\r\n\r\n<table>\r\n<tr>\r\n\r\n<td width=\"300\"/>\r\n\r\n<td>\r\n<form action=\"specific.jsp\" method=\"post\">\r\n".toCharArray();
    _jsp_string24 = "\r\n\r\n\r\n </BODY>\r\n</HTML>\r\n".toCharArray();
    _jsp_string12 = "\r\n	\r\n	<tr>\r\n		<td align=\"center\"> ".toCharArray();
    _jsp_string2 = "\r\n\r\n".toCharArray();
  }
}
