/*
 * JSP generated by Resin-3.1.6 (built Sun, 04 May 2008 03:25:50 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;

public class _fn_0ledger_0alter_0or_0display__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, "/", session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=iso-8859-1");
    request.setCharacterEncoding("ISO-8859-1");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
       
boolean admin_check = false;
boolean fn_check = false;
if(session.getAttribute("user_name").toString().equals("admin_account") & "admin_account".equals(session.getAttribute("pwd").toString()) )
{
	admin_check = true;
}
else if(session.getAttribute("user_name").toString().equals("fn_account") & "fn_account".equals(session.getAttribute("pwd").toString()) )
{
	fn_check = true;
}

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
if(admin_check || fn_check)
{

 
      out.write(_jsp_string2, 0, _jsp_string2.length);
       if(admin_check){ 
      out.write(_jsp_string3, 0, _jsp_string3.length);
       } 
      out.write(_jsp_string1, 0, _jsp_string1.length);
       if(fn_check){ 
      out.write(_jsp_string4, 0, _jsp_string4.length);
       } 
      out.write(_jsp_string5, 0, _jsp_string5.length);
          
      // out.println(request.getParameter("ledgertype"));
      Class.forName("com.mysql.jdbc.Driver");
	  Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/kvk","root","root");
	  String str1="select * from ledgersdata where ledgername=?";
	  PreparedStatement pstmt1=conn.prepareStatement(str1);
	  pstmt1.setString(1,request.getParameter("ledgertype"));
	  ResultSet rs1=pstmt1.executeQuery();
	  while(rs1.next())
	  {
	    rs1.getString(1);
 
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((rs1.getString(1)));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((rs1.getString(2)));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      
	 
	  String str="select * from groups";
	  Statement stmt=conn.createStatement();
	  ResultSet rs=stmt.executeQuery(str);
	  out.println("<select name=under>");
	  out.println("<option selected>");
	  out.println(rs1.getString(3));
	  out.println("</option>");
	  while(rs.next())
	  {
	    out.println("<option>");
		out.println(rs.getString(1));
		out.println("</option>");
	  }
	
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((rs1.getString(4)));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((rs1.getString(5)));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((rs1.getString(6)));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((rs1.getString(7)));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((rs1.getString(8)));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((rs1.getString(9)));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((rs1.getString(10)));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((rs1.getString(11)));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((rs1.getString(12)));
      out.write(_jsp_string18, 0, _jsp_string18.length);
      }
      out.write(_jsp_string19, 0, _jsp_string19.length);
       } 
      out.write(_jsp_string20, 0, _jsp_string20.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7072480922035483583L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("fn_ledger_alter_or_display.jsp"), -1318515628514954323L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string11;
  private final static char []_jsp_string3;
  private final static char []_jsp_string8;
  private final static char []_jsp_string18;
  private final static char []_jsp_string9;
  private final static char []_jsp_string14;
  private final static char []_jsp_string13;
  private final static char []_jsp_string16;
  private final static char []_jsp_string12;
  private final static char []_jsp_string17;
  private final static char []_jsp_string6;
  private final static char []_jsp_string5;
  private final static char []_jsp_string0;
  private final static char []_jsp_string4;
  private final static char []_jsp_string15;
  private final static char []_jsp_string7;
  private final static char []_jsp_string20;
  private final static char []_jsp_string10;
  private final static char []_jsp_string19;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  static {
    _jsp_string11 = ">\r\n   </td>\r\n  </tr>\r\n  <tr>\r\n   <td>\r\n    <font color=\"#573801\" face=\"verdana\" size=\"2\">\r\n	 Address\r\n	</font>\r\n   </td>\r\n   <td>\r\n    <input type=\"text\" name=\"address\" value=".toCharArray();
    _jsp_string3 = "\r\n<form action=\"kvk_finance_main.jsp\" method=\"post\">\r\n".toCharArray();
    _jsp_string8 = ">\r\n  </td>\r\n </tr>\r\n <tr>\r\n  <td>\r\n   <font color=\"#573801\" face=\"verdana\" size=\"2\">\r\n    Under\r\n   </font>\r\n   </td>\r\n   <td>\r\n    ".toCharArray();
    _jsp_string18 = "</option>\r\n	   <option>Dr</option>\r\n	   <option>Cr</option>\r\n	  </select>\r\n	 </td>\r\n	</tr>\r\n	<tr>\r\n	 <td colspan=\"2\" align=\"center\">\r\n	  <input type=\"image\" src=\"images/submit.jpg\">\r\n	 </td>\r\n	</tr>\r\n	".toCharArray();
    _jsp_string9 = "\r\n   </td>\r\n </tr>\r\n <tr>\r\n  <td>\r\n   <font color=\"#573801\" face=\"verdana\" size=\"2\">\r\n    Inventory Values are Effected\r\n   </font>\r\n  </td>\r\n  <td>\r\n   <select name=\"inventoryvalues\">\r\n   <option selected>".toCharArray();
    _jsp_string14 = ">\r\n	</td>\r\n  </tr>\r\n  <tr>\r\n   <td>\r\n    <font color=\"#573801\" face=\"verdana\" size=\"2\">\r\n	 PAN/IT No:\r\n	</font>\r\n   </td>\r\n   <td>\r\n    <input type=\"text\" name=\"panoritno\" value=".toCharArray();
    _jsp_string13 = ">\r\n   </td>\r\n  </tr>\r\n  <tr>\r\n   <td>\r\n    <font color=\"#573801\" face=\"verdana\" size=\"2\">\r\n	 Pin Code\r\n	</font>\r\n    </td>\r\n	<td>\r\n	 <input type=\"text\" name=\"pincode\" value=".toCharArray();
    _jsp_string16 = ">\r\n   </td>\r\n   </tr>\r\n   <tr>\r\n    <td>\r\n	 <font color=\"#573801\" face=\"verdana\" size=\"2\">\r\n	  Opening Balance\r\n	 </font>\r\n	 </td>\r\n	 <td>\r\n	  <input type=\"text\" name=\"openingbalance\" value=".toCharArray();
    _jsp_string12 = ">\r\n   </td>\r\n  </tr>\r\n  <tr>\r\n   <td>\r\n   <font color=\"#573801\" face=\"verdana\" size=\"2\">\r\n    State\r\n   </font>\r\n   </td>\r\n   <td>\r\n    <input type=\"text\" name=\"state\" value=".toCharArray();
    _jsp_string17 = ">\r\n	  <select name=\"type\">\r\n	  <option selected>".toCharArray();
    _jsp_string6 = "\r\n <tr>\r\n  <td width=\"392\">\r\n   <font color=\"#573801\" face=\"verdana\" size=\"2\">\r\n    Ledger Name\r\n   </font>\r\n  </td>\r\n  <td width=\"392\">\r\n   <input type=\"text\" name=\"ledgername\" value=".toCharArray();
    _jsp_string5 = "\r\n\r\n    <tr>\r\n      <td width=\"300\"/>\r\n      <td><input align =\"left\" type=\"image\" src=\"images/home.jpg\"/>\r\n  </form>\r\n  <td width=\"600\"></td>\r\n      <td><input align =\"right\" type=\"image\" src=\"images/back.jpg\" onClick=\"f();\"/>\r\n      </td>\r\n  </tr>\r\n</table>\r\n<h4 align=\"center\"><font color=\"#573801\" face=\"verdana\" size=\"3\"> Ledger Alter  </font></h4>\r\n<table align=\"center\" width=\"800\" border=\"1\" bgcolor=\"#FADFC3\" bordercolor=\"#F0B269\">\r\n <form action=\"fn_ledger_update.jsp\">\r\n ".toCharArray();
    _jsp_string0 = "\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n<title>SVS</title>\r\n\r\n<script type=\"text/javascript\">\r\n\r\n  function f()\r\n  {\r\n	  window.history.go(-1);\r\n  }\r\n  </script>\r\n  \r\n\r\n</head>\r\n\r\n\r\n".toCharArray();
    _jsp_string4 = "\r\n<form action=\"account_operator.jsp\" method=\"post\">\r\n".toCharArray();
    _jsp_string15 = ">\r\n   </td>\r\n  </tr>\r\n  <tr>\r\n   <td>\r\n    <font color=\"#573801\" face=\"verdana\" size=\"2\">\r\n	 Sales Tax No:\r\n	</font>\r\n	\r\n   </td>\r\n   <td>\r\n    <input type=\"text\" name=\"salestaxno\" value=".toCharArray();
    _jsp_string7 = ">\r\n  </td>\r\n </tr>\r\n <tr>\r\n  <td>\r\n   <font color=\"#573801\" face=\"verdana\" size=\"2\">\r\n    Alias\r\n   </font>\r\n  </td>\r\n  <td>\r\n   <input type=\"text\" name=\"alias\" value=".toCharArray();
    _jsp_string20 = "\r\n\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string10 = "</option>\r\n    <option>Yes</option>\r\n	<option>No</option>\r\n   </select>\r\n  </td>\r\n  </tr>\r\n  <tr>\r\n   <td>\r\n    <font color=\"#573801\" face=\"verdana\" size=\"2\">\r\n	 Name\r\n	</font>\r\n   </td>\r\n   <td>\r\n    <input type=\"text\" name=\"name2\" value=".toCharArray();
    _jsp_string19 = "\r\n  </form>\r\n</table>\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n\r\n\r\n\r\n<body background=\"images/bg.jpg\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\r\n\r\n<table width=\"800\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n  <tr>\r\n    <td><img src=\"images/banner.jpg\" width=\"800\"></td>\r\n  </tr>\r\n  \r\n</table>\r\n  <table width=\"800\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n  <tr>\r\n    <td background=\"images/after_main.jpg\" height=\"41\" align=\"center\"><strong><font color=\"#573801\" size=\"3\" face=\"verdana\">Welcome To Finance Department</font>      </strong>    	</td>\r\n  </tr>\r\n</table>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<table>\r\n\r\n  ".toCharArray();
    _jsp_string1 = "\r\n\r\n".toCharArray();
  }
}
