/*
 * JSP generated by Resin-3.1.6 (built Sun, 04 May 2008 03:25:50 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;

public class _headcount__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, "/", session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=iso-8859-1");
    request.setCharacterEncoding("ISO-8859-1");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
       
boolean hr_admin = false;
boolean admin = false;
if(session.getAttribute("user_name").toString().equals("hr_admin") & "hr_admin".equals(session.getAttribute("pwd").toString()) )
{
	hr_admin = true;
}
else if(session.getAttribute("user_name").toString().equals("admin") & "admin".equals(session.getAttribute("pwd").toString()) )
{
	admin = true;
}

      out.write(_jsp_string1, 0, _jsp_string1.length);
       if(hr_admin){ 
      out.write(_jsp_string2, 0, _jsp_string2.length);
       } 
      out.write(_jsp_string3, 0, _jsp_string3.length);
       if(admin){ 
      out.write(_jsp_string4, 0, _jsp_string4.length);
       } 
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
  int malecount=0,femalecount=0,empcount=0,doccount=0,procount=0,postcount=0,techcount=0,grcount=0,ungrcount=0;
  Class.forName("com.mysql.jdbc.Driver");
   Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/kvk","root","root");
   String empcount1="select * from  employee";
    Statement stmt1=conn.createStatement();
	ResultSet rs1=stmt1.executeQuery(empcount1);
	while(rs1.next())
	{
	  empcount++;
	 }
   String malequery="select * from  employee where sex='male'";
    Statement stmt=conn.createStatement();
	ResultSet rs2=stmt.executeQuery(malequery);
	while(rs2.next())
	{
	  malecount++;
	 }
	String femalequery="select * from  employee where sex='female'";
    Statement stmt2=conn.createStatement();
	ResultSet rs3=stmt2.executeQuery(femalequery);
	while(rs3.next())
	{
	  femalecount++;
	 }
	 String malequerya="select * from  employee where qualification='doctorities'";
    Statement stmta=conn.createStatement();
	ResultSet rsa=stmta.executeQuery(malequerya);
	while(rsa.next())
	{
	  doccount++;
	 }
	 String malequery4="select * from  employee where qualification='professionals'";
    Statement stmt4=conn.createStatement();
	ResultSet rs4=stmt4.executeQuery(malequery4);
	while(rs4.next())
	{
	  procount++;
	 }
	 String malequery5="select * from  employee where qualification='post graduates'";
    Statement stmt5=conn.createStatement();
	ResultSet rs5=stmt5.executeQuery(malequery5);
	while(rs5.next())
	{
	  postcount++;
	 }
	 String malequery6="select * from  employee where qualification='technical'";
    Statement stmt6=conn.createStatement();
	ResultSet rs6=stmt6.executeQuery(malequery6);
	while(rs6.next())
	{
	  techcount++;
	 }
	 String malequery7="select * from  employee where qualification='graduates'";
    Statement stmt7=conn.createStatement();
	ResultSet rs7=stmt7.executeQuery(malequery7);
	while(rs7.next())
	{
	  grcount++;
	 }
	 String malequery8="select * from  employee where qualification='under graduates'";
    Statement stmt8=conn.createStatement();
	ResultSet rs8=stmt8.executeQuery(malequery8);
	while(rs8.next())
	{
	  ungrcount++;
	 }
  
      out.write(_jsp_string6, 0, _jsp_string6.length);
       out.println(empcount);
      out.write(_jsp_string7, 0, _jsp_string7.length);
       out.println(empcount);
      out.write(_jsp_string8, 0, _jsp_string8.length);
       out.println(empcount);
      out.write(_jsp_string9, 0, _jsp_string9.length);
       out.println(empcount);
      out.write(_jsp_string10, 0, _jsp_string10.length);
       out.println(malecount);
      out.write(_jsp_string11, 0, _jsp_string11.length);
       out.println(malecount);
      out.write(_jsp_string12, 0, _jsp_string12.length);
       out.println(femalecount);
      out.write(_jsp_string13, 0, _jsp_string13.length);
       out.println(femalecount);
      out.write(_jsp_string14, 0, _jsp_string14.length);
       out.println(doccount);
      out.write(_jsp_string15, 0, _jsp_string15.length);
       out.println(procount);
      out.write(_jsp_string16, 0, _jsp_string16.length);
       out.println(postcount);
      out.write(_jsp_string17, 0, _jsp_string17.length);
       out.println(techcount);
      out.write(_jsp_string18, 0, _jsp_string18.length);
       out.println(grcount);
      out.write(_jsp_string19, 0, _jsp_string19.length);
       out.println(ungrcount);
      out.write(_jsp_string20, 0, _jsp_string20.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7072480922035483583L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("headcount.jsp"), -5939128841595601893L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string14;
  private final static char []_jsp_string1;
  private final static char []_jsp_string9;
  private final static char []_jsp_string11;
  private final static char []_jsp_string13;
  private final static char []_jsp_string7;
  private final static char []_jsp_string6;
  private final static char []_jsp_string16;
  private final static char []_jsp_string2;
  private final static char []_jsp_string19;
  private final static char []_jsp_string8;
  private final static char []_jsp_string3;
  private final static char []_jsp_string17;
  private final static char []_jsp_string12;
  private final static char []_jsp_string20;
  private final static char []_jsp_string5;
  private final static char []_jsp_string10;
  private final static char []_jsp_string18;
  private final static char []_jsp_string15;
  private final static char []_jsp_string4;
  static {
    _jsp_string0 = "\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n<title>SVS</title>\r\n</head>\r\n\r\n\r\n".toCharArray();
    _jsp_string14 = "</td>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">Doctorates</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string1 = "\r\n\r\n<body background=\"images/bg.jpg\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\r\n<table width=\"804\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n  <tr>\r\n    <td width=\"800\"><img src=\"images/banner.jpg\" width=\"807\"></td>\r\n  </tr>\r\n  <!--  <tr>\r\n   <td>\r\n  <table width=\"800\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n  <tr>\r\n    <td><img src=\"images/finance.jpg\" width=\"119\"></td>\r\n    <td><img src=\"images/project-management.jpg\" width=\"119\"></td>\r\n    <td><img src=\"images/inventory.jpg\" width=\"119\"></td>\r\n    <td><img src=\"images/sales.jpg\" width=\"119\"></td>\r\n    <td><img src=\"images/maintenance.jpg\" width=\"119\"></td>\r\n    <td><img src=\"images/power.jpg\" width=\"119\"></td>\r\n    <td><img src=\"images/human-resources.jpg\" width=\"119\"></td>\r\n  </tr>\r\n</table>\r\n\r\n   </td>\r\n  </tr>-->\r\n  \r\n</table>\r\n<table align=\"center\" background=\"images/bg.jpg\" width=\"800\">\r\n<tr>\r\n<td>\r\n\r\n".toCharArray();
    _jsp_string9 = "</td>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">On Roll at the end of Period </font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string11 = "</td>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">Males at the End of Period</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string13 = "</td>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">Females at the End of Day</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string7 = "</td>\r\n	\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">Add:New Joinings</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string6 = " \r\n <h3 align=\"center\"><font color=\"#573801\">Head Count</font></h3>\r\n <table width=\"800\" border=\"1\" align=\"center\" bgcolor=\"#FADFC3\" bordercolor=\"#F0B269\">\r\n   <tr>\r\n     <th scope=\"col\"><font color=\"#573801\" size=\"4\">Particulars</font></th>\r\n     <th scope=\"col\"><font color=\"#573801\" size=\"4\">Jul-07</font></th>\r\n     <th scope=\"col\"><font color=\"#573801\" size=\"4\">Aug-07</font></th>\r\n     <th scope=\"col\"><font color=\"#573801\" size=\"4\">Sep-07</font></th>\r\n     <th scope=\"col\"><font color=\"#573801\" size=\"4\">Oct-07</font></th>\r\n     <th scope=\"col\"><font color=\"#573801\" size=\"4\">Nov-07</font></th>\r\n     <th scope=\"col\"><font color=\"#573801\" size=\"4\">Dec-07</font></th>\r\n     <th scope=\"col\"><font color=\"#573801\" size=\"4\">Jan-08</font></th>\r\n	      <th scope=\"col\"><font color=\"#573801\" size=\"4\">Feb-08</font></th>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">On Roll Employee</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string16 = "</td>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">Post Graduates</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string2 = "\r\n<form action=\"specific.jsp\" method=\"post\">\r\n <input type=\"hidden\" name=\"username\" value=\"hr_admin\">\r\n <input type=\"hidden\" name=\"password\" value=\"hr_admin\">\r\n  <input type=\"image\" src=\"images/home.jpg\">\r\n </form> \r\n ".toCharArray();
    _jsp_string19 = "</td>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">Under Graduates</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string8 = "</td>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">On Roll at the end of Period</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string3 = "\r\n \r\n ".toCharArray();
    _jsp_string17 = "</td>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">Technical</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string12 = "</td>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">Females at the Beginning</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>".toCharArray();
    _jsp_string20 = "</td>\r\n   </tr>\r\n </table>\r\n </td>\r\n </tr>\r\n</table>\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string5 = "\r\n\r\n ".toCharArray();
    _jsp_string10 = "</td>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">Males at the Beginning</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string18 = "</td>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">Graduates</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string15 = "</td>\r\n   </tr>\r\n   <tr>\r\n     <td><font color=\"#573801\" size=\"4\">Professionals</font></td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n     <td>--</td>\r\n	 <td>".toCharArray();
    _jsp_string4 = "\r\n <form action=\"humanresource1.jsp\" method=\"post\">\r\n <input type=\"hidden\" name=\"username\" value=\"admin\">\r\n <input type=\"hidden\" name=\"password\" value=\"admin\">\r\n  <input type=\"image\" src=\"images/home.jpg\">\r\n </form> \r\n".toCharArray();
  }
}
