/*
 * JSP generated by Resin-3.1.6 (built Sun, 04 May 2008 03:25:50 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.util.Vector.*;
import java.sql.*;

public class _in_0purchase_0returns_0submit__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
       
if(session.getAttribute("user_name").toString().equals("inventory") & "inventory".equals(session.getAttribute("pwd").toString()) )
{

 
      out.write(_jsp_string1, 0, _jsp_string1.length);
       Class.forName("com.mysql.jdbc.Driver");
   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/kvk","root","root");
 
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
	
	String dt1=request.getParameter("date1");
	
	String sp=request.getParameter("partyname");
	
	String sq=request.getParameter("quat_no");
	
	String si=request.getParameter("item_code");
	
	String s1=request.getParameter("nameofitem");
	//out.println(s4);
	String s2=request.getParameter("qty");
	//out.println(s5);
	
	String s3=request.getParameter("units");
	//out.println(s7);
	String s4=request.getParameter("rate");
	//out.println(s6);
	String s5=request.getParameter("amount");
	//out.println(s8);
	String s6=request.getParameter("narration");
	//out.println(s9);
	
	Integer ii=Integer.parseInt(s2);
	//out.println("i1 : "+ ii);

	Double d1 = Double.parseDouble(s4);
	//out.println("d1 : "+ d1);

	Double d2 = Double.parseDouble(s5);
	//out.println("d2 : "+ d2);


	Statement st=con.createStatement();

	String q1="insert into in_purchase_returns  values('"+dt1+"' , '"+sp+"' ,'"+sq+"' ,'"+si+"' ,'"+s1+"', "+ii+" ,'"+s3+"' ,"+d1+","+d2+",'"+s6+"')";

	
	int k=st.executeUpdate(q1);
	
	if(k==1 )
	out.println("success");

	
	

      out.write(_jsp_string3, 0, _jsp_string3.length);
       } 
      out.write(_jsp_string4, 0, _jsp_string4.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7072480922035483583L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("in_purchase_returns_submit.jsp"), -4200587517333362719L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  private final static char []_jsp_string4;
  private final static char []_jsp_string1;
  static {
    _jsp_string0 = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n\r\n\r\n<HTML>\r\n</HEAD>\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n\r\n <table width=\"800\"  border = \"0\" cellspacing = \"0\" cellpadding = \"0\" align =\"center\">\r\n <tr>\r\n <td>\r\n	<img src = \"images/banner.jpg\" width = \"800\"></td>\r\n </tr>\r\n </table>\r\n\r\n \r\n\r\n \r\n\r\n <table width = \"800\" border = \"0\" cellspacing = \"0\" cellpadding = \"0\" align = \"center\">\r\n <tr>\r\n <td background = \"images/after_main.jpg\" height = \"41\" align = \"center\" >\r\n	<strong> <font color = \"#573801\" size = \"3\" face = \"verdana\"> Welcome To Inventory Department</font></strong>\r\n </td>\r\n </tr>\r\n </table>\r\n\r\n\r\n<p>&nbsp;</p>\r\n \r\n\r\n ".toCharArray();
    _jsp_string3 = "\r\n\r\n<center>\r\n\r\n<strong> <font color = \"#573801\" size = \"3\" face = \"verdana\">Successfully Inserted</font></strong>\r\n</center>\r\n<center>\r\n<form action=\"in_purchases.jsp\" method=\"post\">\r\n\r\n<input type=\"submit\"   name=\"voucher\" value=\"  Back \" />\r\n\r\n</form>\r\n</center>\r\n\r\n".toCharArray();
    _jsp_string4 = "\r\n </BODY>\r\n</HTML>\r\n".toCharArray();
    _jsp_string1 = "\r\n \r\n\r\n <BODY background=\"images/bg.jpg\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\r\n \r\n \r\n\r\n\r\n\r\n".toCharArray();
  }
}
