/*
 * JSP generated by Resin-3.1.6 (built Sun, 04 May 2008 03:25:50 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.util.Vector.*;
import java.sql.*;
import java.text.*;

public class _profit_226loss_0main__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
       Class.forName("com.mysql.jdbc.Driver");
   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/kvk","root","root");
   Statement st=con.createStatement();
   
      out.write(_jsp_string1, 0, _jsp_string1.length);
       
boolean admin_check = false;
boolean admin = false;
if(session.getAttribute("user_name").toString().equals("admin_account") & "admin_account".equals(session.getAttribute("pwd").toString()) )
{
	admin_check = true;
}
else if(session.getAttribute("user_name").toString().equals("admin") & "admin".equals(session.getAttribute("pwd").toString()) )
{
	admin = true;
}

      out.write(_jsp_string2, 0, _jsp_string2.length);
      
if(admin_check || admin)
{

 
      out.write(_jsp_string3, 0, _jsp_string3.length);
       if(admin_check){ 
      out.write(_jsp_string4, 0, _jsp_string4.length);
       } 
      out.write(_jsp_string2, 0, _jsp_string2.length);
       if(admin){ 
      out.write(_jsp_string5, 0, _jsp_string5.length);
       } 
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
					String t = "gfsd";
					double dr_gr_tot=0.0;
					double open_stk_b=0.0;
					
					DecimalFormat df = new DecimalFormat("#.##");
					
					////
					
					
					String ps=" select sum(balance) from current_assets where  under='PurchaseAccounts'  ";
				ResultSet prs=st.executeQuery(ps);
				prs.next();
				
				double purchase_b=prs.getDouble(1);
				
				
				
				/////
				
				String dpys=" select sum(balance) from current_assets where  under='DirectExpenses' ";
				ResultSet dpyrs=st.executeQuery(dpys);
				dpyrs.next();
				
				double dir_exp_b=0.0;
				
				dir_exp_b = dpyrs.getDouble(1);
				////
				
				String pys=" select sum(balance) from current_assets where under='IndirectExpenses' ";
				ResultSet pyrs=st.executeQuery(pys);
				pyrs.next();
				
				double indir_exp_b=0;
				indir_exp_b = pyrs.getDouble(1);
				
				//String pys1=" select particulars from voucher_payment ,ledgersdata where ledgername=particulars and under='IndirectExpenses' ";
				//ResultSet pyrs1=st.executeQuery(pys1);
				//while(pyrs1.next())
				//{
					//out.println(pyrs1.getString(1));
				//session.setAttribute("parti",pyrs1.getString(1));
				//}
				
				
				/////
				
				
				String ss=" select sum(balance) from current_assets where  under='SalesAccounts'  ";
				ResultSet srs=st.executeQuery(ss);
				srs.next();
				
				double sales_b = 0;
				sales_b = srs.getDouble(1);
				
				
				/////
				
				
				String sdin=" select sum(balance) from current_assets where  under='DirectIncomes'  ";
				ResultSet sdinrs=st.executeQuery(sdin);
				sdinrs.next();
				
				double dir_income_b=0.0;
				dir_income_b = sdinrs.getDouble(1);
				
				////
				
				
				
				
				
				String sindin=" select sum(balance) from current_assets where  under='IndirectIncomes'  ";
				ResultSet sindinrs=st.executeQuery(sindin);
				sindinrs.next();
				
				double indir_income_b=0.0;
				indir_income_b = sindinrs.getDouble(1);
				
				
				/////
				
				String cs=" select sum(balance) from closing_stock";
				ResultSet crs=st.executeQuery(cs);
				crs.next();
				
				double cl_stk_b=0;
				cl_stk_b = crs.getDouble(1);
				
				////
				
				
					dr_gr_tot = purchase_b + dir_exp_b + open_stk_b;
					
					double cr_grs_tot = 0.0;
					
					cr_grs_tot = sales_b + dir_income_b + cl_stk_b  ;
					
					double tot = 0.0;
					
					double gross_prf_b = 0.00;
					double gross_prf_c = 0.00;
				
				if( dr_gr_tot < cr_grs_tot)
				{
					gross_prf_c = cr_grs_tot - dr_gr_tot ;
					t = "dr";
					tot = cr_grs_tot;
				}
				else
				{
					gross_prf_b = dr_gr_tot - cr_grs_tot ;
					t = "cr"; 
					tot = dr_gr_tot;
				}
				//out.println("greater :" + t);
				
				///////
				
				double net_loss = 0.0;
				double net_profit = 0.0;
				double net_tot = 0.0;
				double dr_net = 0.0;
				double cr_net = 0.0;
				
				dr_net =  indir_exp_b + gross_prf_b;
				cr_net = gross_prf_c + indir_income_b;
				
				session.setAttribute("netpr" , net_profit);
				session.setAttribute("netls" , net_loss);
				String net = null;
				if(dr_net < cr_net)
				{
					net_profit = cr_net - dr_net;
					net_tot = cr_net;
					net="pr";
					session.setAttribute("netpr" , net_profit);
					//out.println(net_profit);
				}
				else
				{
					net_loss = dr_net - cr_net;
					net_tot = dr_net;
					net="ls";
					session.setAttribute("netls" , net_loss);
					//out.println(net_loss);
					
				}
				
				 
				
				
				
				
				
				
				
				
				
				

      out.write(_jsp_string7, 0, _jsp_string7.length);
       out.print(open_stk_b); 
      out.write(_jsp_string8, 0, _jsp_string8.length);
      
				
				out.print(purchase_b);
			
      out.write(_jsp_string9, 0, _jsp_string9.length);
      	
					
					out.print(dir_exp_b);
				
      out.write(_jsp_string10, 0, _jsp_string10.length);
       
				if(t.equals("dr"))
				{
			 
      out.write(_jsp_string11, 0, _jsp_string11.length);
      
					
					
					out.print(df.format(gross_prf_c));
				
      out.write(_jsp_string12, 0, _jsp_string12.length);
       } 
      out.write(_jsp_string13, 0, _jsp_string13.length);
      
				
				out.print("---------------");
			
      out.write(_jsp_string14, 0, _jsp_string14.length);
      
				
				out.print(df.format(tot));
			
      out.write(_jsp_string15, 0, _jsp_string15.length);
      
				
				out.print("---------------");
			
      out.write(_jsp_string16, 0, _jsp_string16.length);
       
				if(t.equals("cr"))
				{
			 
      out.write(_jsp_string17, 0, _jsp_string17.length);
      
					//double gross_prf_c = cr_grs_tot - dr_gr_tot ;
					
					out.print(df.format(gross_prf_b));
				
      out.write(_jsp_string12, 0, _jsp_string12.length);
       } 
      out.write(_jsp_string18, 0, _jsp_string18.length);
      
				
				out.print(indir_exp_b);
			
      out.write(_jsp_string19, 0, _jsp_string19.length);
      
				if(net.equals("pr"))
				{
			
      out.write(_jsp_string20, 0, _jsp_string20.length);
      out.print(df.format(net_profit));
      out.write(_jsp_string21, 0, _jsp_string21.length);
       } 
      out.write(_jsp_string22, 0, _jsp_string22.length);
      
				
				out.print(sales_b);
			
      out.write(_jsp_string23, 0, _jsp_string23.length);
      
					
					out.print(dir_income_b);
				
      out.write(_jsp_string24, 0, _jsp_string24.length);
      
				
				out.print(cl_stk_b);
			
      out.write(_jsp_string25, 0, _jsp_string25.length);
       
						 
			if(t.equals("cr"))
			{
			
      out.write(_jsp_string26, 0, _jsp_string26.length);
      
					out.print(gross_prf_b);
				
      out.write(_jsp_string12, 0, _jsp_string12.length);
       } 
      out.write(_jsp_string13, 0, _jsp_string13.length);
      
				
				out.print("---------------");
			
      out.write(_jsp_string27, 0, _jsp_string27.length);
      
					
					out.print(df.format(tot));
				
      out.write(_jsp_string28, 0, _jsp_string28.length);
      
				
				out.print("---------------");
			
      out.write(_jsp_string19, 0, _jsp_string19.length);
       
						 
			if(t.equals("dr"))
			{
			
      out.write(_jsp_string29, 0, _jsp_string29.length);
      
					out.print(df.format(gross_prf_c));
				
      out.write(_jsp_string12, 0, _jsp_string12.length);
       } 
      out.write(_jsp_string30, 0, _jsp_string30.length);
      
				
				out.print(indir_income_b);
			
      out.write(_jsp_string31, 0, _jsp_string31.length);
      
				if(net.equals("ls"))
				{
			
      out.write(_jsp_string32, 0, _jsp_string32.length);
      out.print(df.format(net_loss));
      out.write(_jsp_string21, 0, _jsp_string21.length);
        } 
      out.write(_jsp_string33, 0, _jsp_string33.length);
       out.println(df.format(net_tot)); 
      out.write(_jsp_string34, 0, _jsp_string34.length);
       out.println(df.format(net_tot)); 
      out.write(_jsp_string35, 0, _jsp_string35.length);
       } 
      out.write(_jsp_string36, 0, _jsp_string36.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7072480922035483583L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("Profit&Loss_main.jsp"), -1904541413854009324L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string4;
  private final static char []_jsp_string0;
  private final static char []_jsp_string30;
  private final static char []_jsp_string13;
  private final static char []_jsp_string8;
  private final static char []_jsp_string7;
  private final static char []_jsp_string32;
  private final static char []_jsp_string18;
  private final static char []_jsp_string15;
  private final static char []_jsp_string34;
  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string11;
  private final static char []_jsp_string14;
  private final static char []_jsp_string35;
  private final static char []_jsp_string20;
  private final static char []_jsp_string29;
  private final static char []_jsp_string21;
  private final static char []_jsp_string28;
  private final static char []_jsp_string10;
  private final static char []_jsp_string25;
  private final static char []_jsp_string24;
  private final static char []_jsp_string5;
  private final static char []_jsp_string19;
  private final static char []_jsp_string23;
  private final static char []_jsp_string9;
  private final static char []_jsp_string12;
  private final static char []_jsp_string26;
  private final static char []_jsp_string22;
  private final static char []_jsp_string31;
  private final static char []_jsp_string33;
  private final static char []_jsp_string16;
  private final static char []_jsp_string27;
  private final static char []_jsp_string6;
  private final static char []_jsp_string17;
  private final static char []_jsp_string2;
  private final static char []_jsp_string36;
  static {
    _jsp_string4 = "\r\n<form action=\"kvk_finance_main.jsp\" method=\"post\">\r\n".toCharArray();
    _jsp_string0 = "<!-- Strip whitespace -->\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string30 = "\r\n			\r\n			<tr ><td witdh=\"250\"><a href=\"#\"><strong> <font   face=\"Times New Roman, Times, serif\">Indirect&nbsp;Income</font></strong></a></td> <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string13 = "\r\n			\r\n			<tr ><td witdh=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\"> </font></strong></td> <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string8 = "\r\n				\r\n			</td></tr> \r\n			<tr ><td witdh=\"250\"><a href=\"purchase_accounts.jsp\"><strong> <font   face=\"Times New Roman, Times, serif\">Purchase&nbsp;Accounts</font></strong></a></td> <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string7 = "\r\n \r\n\r\n\r\n\r\n<table width=\"800\"   align=\"center\" >\r\n\r\n<tr>\r\n\r\n<td>\r\n	<table width=\"800\" align=\"center\" height=\"400\"  border=\"1\"  bgcolor=\"#FADFC3\" bordercolor=\"#F0B269\" >\r\n	<tr>\r\n		<td><table height=\"50\"><tr><td width=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\">DR </font></strong></td> <td width=\"350\"><strong> <font   face=\"Times New Roman, Times, serif\"> Particulars</font></strong></td></tr></table></td>\r\n		<td><table height=\"50\"><tr><td width=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\">CR </font></strong></td> <td width=\"350\"><strong> <font   face=\"Times New Roman, Times, serif\"> Particulars</font></strong></td></tr></table></td>\r\n	</tr>\r\n	<tr>\r\n	<td>\r\n		<table width=\"400\"  border=\"0\" height=\"397\" bgcolor=\"#FADFC3\" bordercolor=\"#F0B269\" cellpadding=\"0\"  cellspacing=\"0\">	\r\n			<tr ><td witdh=\"250\"><a href=\"#\"><strong> <font   face=\"Times New Roman, Times, serif\">Opening Stock</font></strong></a></td> <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string32 = "\r\n			\r\n			<tr ><td witdh=\"250\"><strong> <font    color=\"#F4362D\" face=\"Times New Roman, Times, serif\">Net Loss</font></strong></td> <td align=\"right\" width=\"300\"  ><font color=\"F4362D\">".toCharArray();
    _jsp_string18 = "\r\n			\r\n			<tr ><td witdh=\"250\"><a href=\"indirect_expenses.jsp\"><strong> <font   face=\"Times New Roman, Times, serif\">Indirect&nbsp;Expenses</font></strong></a></td> <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string15 = "\r\n			</td></tr>\r\n			\r\n			<tr ><td witdh=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\"> </font></strong></td> <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string34 = "</font></strong></td></tr></table></td>\r\n		<td><table height=\"50\"><tr><td width=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\">Total</font></strong></td>  <td width=\"350\" align=\"right\"><strong> <font   face=\"Times New Roman, Times, serif\"> ".toCharArray();
    _jsp_string1 = "\r\n   \r\n<HTML>\r\n <HEAD>\r\n \r\n  <title>SVS</title>\r\n  \r\n  <script type=\"text/javascript\">\r\n\r\n  function f()\r\n  {\r\n	  window.history.go(-1);\r\n  }\r\n  </script>\r\n  \r\n  \r\n   </HEAD>\r\n   \r\n   \r\n".toCharArray();
    _jsp_string3 = "\r\n\r\n\r\n\r\n <BODY background=\"images/bg.jpg\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\r\n \r\n \r\n\r\n  <table width=\"800\"  border = \"0\" cellspacing = \"0\" cellpadding = \"0\" align =\"center\">\r\n <tr>\r\n 	<td><img src = \"images/banner.jpg\" width = \"800\"></td>\r\n </tr>\r\n </table>\r\n\r\n <table width = \"800\" border = \"0\" cellspacing = \"0\" cellpadding = \"0\" align = \"center\">\r\n <tr>\r\n <td background = \"images/after_main.jpg\" height = \"41\" align = \"center\" ><strong> <font color = \"#573801\" size = \"3\" \r\n face = \"verdana\"> Welcome To Finance Department</font></strong> </td>\r\n </tr>\r\n </table>\r\n<p>&nbsp;</p>\r\n\r\n<table align=\"center\"    >\r\n<tr>\r\n <td ><strong> <font  face = \"verdana\" size = \"3\" color=\"#573801\" >Profit & Loss A/C  Details</font></strong>\r\n</td>\r\n</tr>\r\n\r\n</table>\r\n\r\n<table>\r\n\r\n".toCharArray();
    _jsp_string11 = "\r\n			<tr ><td witdh=\"250\"><strong> <font  color=\"#4B5BEF\" face=\"Times New Roman, Times, serif\">Gross&nbsp;Profit&nbsp;c/o</font></strong></td> <td align=\"right\" width=\"300\"><font  color=\"#4B5BEF\">\r\n				".toCharArray();
    _jsp_string14 = "\r\n			</td></tr>\r\n			\r\n			\r\n			<tr ><td witdh=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\">Total </font></strong></td> <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string35 = "</font></strong></td></tr></table></td>\r\n	</tr>\r\n	\r\n	</table>\r\n\r\n</td>\r\n</tr>\r\n</table>\r\n\r\n\r\n".toCharArray();
    _jsp_string20 = "\r\n			\r\n			<tr ><td witdh=\"250\"><strong> <font   color=\"#009349\" face=\"Times New Roman, Times, serif\">Net Profit</font></strong></td> <td align=\"right\" width=\"300\"><font   color=\"#009349\">".toCharArray();
    _jsp_string29 = "\r\n			<tr ><td witdh=\"250\"><strong> <font   color=\"#4B5BEF\" face=\"Times New Roman, Times, serif\">Gross&nbsp;Profit&nbsp;b/f</font></strong></td> <td align=\"right\" width=\"300\"><font  color=\"#4B5BEF\">\r\n				".toCharArray();
    _jsp_string21 = "</font></td></tr>\r\n			".toCharArray();
    _jsp_string28 = "\r\n			</td></tr>\r\n			<tr ><td witdh=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\"> </font></strong></td> <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string10 = "\r\n			</td></tr>\r\n			".toCharArray();
    _jsp_string25 = "</td>\r\n			</tr>\r\n			\r\n			\r\n			\r\n			".toCharArray();
    _jsp_string24 = "\r\n			</td></tr>\r\n			<tr ><td witdh=\"250\"><a href=\"closing_stock.jsp\"><strong> <font   face=\"Times New Roman, Times, serif\">Closing&nbsp;Stock</font></strong></a></td> <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string5 = "\r\n<form action=\"account1_admin.jsp\" method=\"post\">\r\n".toCharArray();
    _jsp_string19 = "\r\n			</td></tr>\r\n			\r\n			<tr ><td  height=\"50\"></td> </tr> \r\n			\r\n			".toCharArray();
    _jsp_string23 = "</td>\r\n			</tr>\r\n			<tr ><td witdh=\"250\"><a href=\"#\"><strong> <font   face=\"Times New Roman, Times, serif\">Direct&nbsp;Income</font></strong></a></td> <td align=\"right\" width=\"300\">\r\n				".toCharArray();
    _jsp_string9 = "\r\n			</td></tr>\r\n			\r\n			\r\n			<tr >\r\n			  <td witdh=\"250\"><a href=\"direct_expenses.jsp\"><strong> <font   face=\"Times New Roman, Times, serif\">Direct&nbsp;Expenses</font></strong></a></td> \r\n			  <td align=\"right\" width=\"300\">\r\n				".toCharArray();
    _jsp_string12 = "</font>\r\n			</td></tr>\r\n			".toCharArray();
    _jsp_string26 = "\r\n			<tr >\r\n			  <td witdh=\"250\"><strong> <font   color=\"#4B5BEF\" face=\"Times New Roman, Times, serif\">Gross&nbsp;Loss&nbsp;c/o</font></strong></td> \r\n			  <td align=\"right\" width=\"300\"><font   color=\"#4B5BEF\" >\r\n				".toCharArray();
    _jsp_string22 = "\r\n			\r\n			\r\n			\r\n		</table>\r\n	</td>\r\n	<td>\r\n		<table width=\"400\" border=\"0\" height=\"397\" bgcolor=\"#FADFC3\" bordercolor=\"#F0B269\" cellpadding=\"0\" cellspacing=\"0\" >\r\n			<tr >\r\n			  <td witdh=\"250\"><a href=\"sales_accounts.jsp\"><strong> <font   face=\"Times New Roman, Times, serif\">Sales&nbsp;Accounts</font></strong></a></td> \r\n			  <td align=\"right\" width=\"300\">\r\n			".toCharArray();
    _jsp_string31 = "</td>\r\n			</tr>\r\n			\r\n			\r\n			<tr ><td  height=\"50\"></td> </tr> \r\n			\r\n			".toCharArray();
    _jsp_string33 = "\r\n			\r\n			\r\n			 \r\n		</table>\r\n	</td>\r\n	</tr>\r\n	\r\n	\r\n	\r\n	<tr>\r\n		<td><table height=\"50\"><tr><td width=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\">Total</font></strong></td> <td width=\"350\" align=\"right\"><strong> <font   face=\"Times New Roman, Times, serif\"> ".toCharArray();
    _jsp_string16 = "\r\n			</td></tr>\r\n			\r\n			<tr ><td  height=\"50\"></td> </tr> \r\n			\r\n			\r\n			\r\n			\r\n			".toCharArray();
    _jsp_string27 = "\r\n			</td></tr>\r\n			\r\n			\r\n			<tr ><td witdh=\"250\"><strong> <font   face=\"Times New Roman, Times, serif\">Total </font></strong></td> <td align=\"right\" width=\"300\">\r\n				".toCharArray();
    _jsp_string6 = "\r\n\r\n<tr>\r\n<td width=\"300\"/>\r\n\r\n<td>\r\n<input align =\"left\" type=\"image\" src=\"images/home.jpg\"/>\r\n</form>\r\n</td>\r\n<td width=\"600\"></td>\r\n<td>\r\n<input align =\"right\" type=\"image\" src=\"images/back.jpg\" onClick=\"f();\"/>\r\n\r\n</td>\r\n\r\n</tr>\r\n</table>\r\n\r\n \r\n\r\n ".toCharArray();
    _jsp_string17 = "\r\n			<tr >\r\n			  <td witdh=\"250\"><strong> <font   color=\"#4B5BEF\" face=\"Times New Roman, Times, serif\">Gross&nbsp;Loss&nbsp;b/f</font></strong></td> \r\n			  <td align=\"right\" width=\"300\"><font   color=\"#4B5BEF\">\r\n				".toCharArray();
    _jsp_string2 = "\r\n\r\n".toCharArray();
    _jsp_string36 = "\r\n\r\n </BODY>\r\n</HTML>\r\n".toCharArray();
  }
}
